// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: protos/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenRequest) Reset() {
	*x = ValidateAccessTokenRequest{}
	mi := &file_protos_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenRequest) ProtoMessage() {}

func (x *ValidateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_protos_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAccessTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenResponse) Reset() {
	*x = ValidateAccessTokenResponse{}
	mi := &file_protos_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenResponse) ProtoMessage() {}

func (x *ValidateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_protos_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAccessTokenResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ValidateAccessTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_protos_auth_auth_proto protoreflect.FileDescriptor

const file_protos_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x16protos/auth/auth.proto\x12\x04auth\"2\n" +
	"\x1aValidateAccessTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"K\n" +
	"\x1bValidateAccessTokenResponse\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2i\n" +
	"\vAuthService\x12Z\n" +
	"\x13ValidateAccessToken\x12 .auth.ValidateAccessTokenRequest\x1a!.auth.ValidateAccessTokenResponseB5Z3github.com/himanshu3889/discore-backend/protos/authb\x06proto3"

var (
	file_protos_auth_auth_proto_rawDescOnce sync.Once
	file_protos_auth_auth_proto_rawDescData []byte
)

func file_protos_auth_auth_proto_rawDescGZIP() []byte {
	file_protos_auth_auth_proto_rawDescOnce.Do(func() {
		file_protos_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_auth_proto_rawDesc), len(file_protos_auth_auth_proto_rawDesc)))
	})
	return file_protos_auth_auth_proto_rawDescData
}

var file_protos_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_auth_auth_proto_goTypes = []any{
	(*ValidateAccessTokenRequest)(nil),  // 0: auth.ValidateAccessTokenRequest
	(*ValidateAccessTokenResponse)(nil), // 1: auth.ValidateAccessTokenResponse
}
var file_protos_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.ValidateAccessToken:input_type -> auth.ValidateAccessTokenRequest
	1, // 1: auth.AuthService.ValidateAccessToken:output_type -> auth.ValidateAccessTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_auth_auth_proto_init() }
func file_protos_auth_auth_proto_init() {
	if File_protos_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_auth_proto_rawDesc), len(file_protos_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_auth_proto_goTypes,
		DependencyIndexes: file_protos_auth_auth_proto_depIdxs,
		MessageInfos:      file_protos_auth_auth_proto_msgTypes,
	}.Build()
	File_protos_auth_auth_proto = out.File
	file_protos_auth_auth_proto_goTypes = nil
	file_protos_auth_auth_proto_depIdxs = nil
}
